global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: app_metrics
    metrics_path: /private/metrics
    static_configs:
      - targets:
          - app-1:8080
          - app-2:8080
          - app-3:8080
          - app-4:8080
