global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: app_metrics
    metrics_path: /private/metrics
    static_configs:
      - targets:
          - app:8080
          - second:8080