{
 "title": "Kafka State Store",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Keys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated number of keys (per table)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_estimate_num_keys{instance=~\"$instance\"}) by (pod, rocksdb_state_id)",
       "legendFormat": "{{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Estimated number of keys total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_estimate_num_keys{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memtables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size All mem tables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_size_all_mem_tables{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Size All mem tables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_size_all_mem_tables{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active mem tables in Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_cur_size_active_mem_table{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Immutable mem tables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_num_immutable_mem_table{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}} - {{rocksdb_state_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SST Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "The total size SST files (per table)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_total_sst_files_size{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Live SST Files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_live_sst_files_size{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Open SST Files total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_number_open_files_total{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Error files total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_number_file_errors_total{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}} - {{rocksdb_state_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compaction pending",
     "type": "timeseries",
     "description": "1 if at least 1 is pending, 0 if none",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_compaction_pending{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}} - {{rocksdb_state_id}}"
      }
     ]
    },
    {
     "title": "Running compaction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum(kafka_stream_state_num_running_compactions{instance=~\"$instance\"}) by (instance, rocksdb_state_id)",
       "legendFormat": "{{instance}} - {{rocksdb_state_id}}"
      }
     ]
    }
   ]
  }
 ]
}