{
 "title": "Kafka Consumer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Heartbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heartbeat total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(kafka_consumer_coordinator_heartbeat_total{application=\"$application\",instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Heartbeat rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_coordinator_heartbeat_rate{application=\"$application\",instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Heartbeat response time max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_coordinator_heartbeat_response_time_max{application=\"$application\",instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Last heartbeat seconds ago",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_coordinator_last_heartbeat_seconds_ago{application=\"$application\",instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Fetch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes consumed total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_bytes_consumed_total{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Bytes consumed rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_bytes_consumed_rate{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_fetch_total{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch latency avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_fetch_latency_avg{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch latency max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_fetch_latency_max{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_fetch_rate{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch size per request avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_fetch_size_avg{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch size per request max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_fetch_size_max{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch throttle time avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_fetch_throttle_time_avg{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch throttle time max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_fetch_throttle_time_max{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch records consumed total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_consumed_total{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch records consumed rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_consumed_rate{application=\"$application\", instance=\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch records lag per partition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_lag{application=\"$application\", instance=\"$instance\"}) by (client_id, topic, partition)",
       "legendFormat": "{{client_id}} - {{topic}} - {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer byte total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_incoming_byte_total{client_id!~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer byte rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_outgoing_byte_rate{client_id!~\".*restore-consumer\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Outgoing - {{instance}}"
      },
      {
       "expr": "sum(kafka_consumer_incoming_byte_rate{client_id!~\".*restore-consumer\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Incoming - {{instance}}"
      },
      {
       "expr": "sum(kafka_consumer_outgoing_byte_rate{client_id!~\".*restore-consumer\", instance=~\"$instance\"})",
       "legendFormat": "Outgoing - total"
      },
      {
       "expr": "sum(kafka_consumer_incoming_byte_rate{client_id!~\".*restore-consumer\", instance=~\"$instance\"})",
       "legendFormat": "Incoming - total"
      }
     ]
    },
    {
     "title": "Consumer total number of requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_request_total{client_id!~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_request_rate{client_id!~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer request size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_request_size_avg{client_id!~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer request max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_request_size_max{client_id!~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Record Consumed Rate Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_consumed_rate{client_id!~\".*restore-consumer\", topic=~\".+\", instance=~\"$instance\"}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Consumer Lag per Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(instance) (kafka_consumer_fetch_manager_records_lag{topic=~\".+\", client_id!~\".*restore-consumer\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Restore Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer byte total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_incoming_byte_total{client_id=~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer byte total rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_outgoing_byte_rate{client_id=~\".*restore-consumer\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Outgoing - {{instance}}"
      },
      {
       "expr": "sum(kafka_consumer_incoming_byte_rate{client_id=~\".*restore-consumer\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Incoming - {{instance}}"
      },
      {
       "expr": "sum(kafka_consumer_outgoing_byte_rate{client_id=~\".*restore-consumer\", instance=~\"$instance\"})",
       "legendFormat": "Outgoing - total"
      },
      {
       "expr": "sum(kafka_consumer_incoming_byte_rate{client_id=~\".*restore-consumer\", instance=~\"$instance\"})",
       "legendFormat": "Incoming - total"
      }
     ]
    },
    {
     "title": "Consumer total number of requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_request_total{client_id=~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_request_rate{client_id=~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer request size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_request_size_avg{client_id=~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer request max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_request_size_max{client_id=~\".*restore-consumer\", instance=~\"$instance\"}) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Record Consumed Rate Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_consumed_rate{client_id=~\".*restore-consumer\", topic=~\".+\", instance=~\"$instance\"}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Consumer Lag per Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(instance) (kafka_consumer_fetch_manager_records_lag{topic=~\".+\", client_id=~\".*restore-consumer\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rebalancing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  }
 ]
}