version: '3.8'

services:
  prometheus:
    build:
      context: prometheus
      args:
        ENVIRONMENT: local
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  # default user and password: admin
  grafana:
    image: grafana/grafana:8.5.2
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
